Repository Switch-Switch/switchswitch, pull requests merged in 2024-09, with the labels that each got.

#13 Gateway mvc에서 webflux 로 변경
  api-gateway/build.gradle
  api-gateway/src/main/resources/application.yml
  switchswitch-common/build.gradle
Labels: ⚙️ Refactoring

#14 JWT member_id로 변경
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/auth/controller/AuthController.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/auth/service/AuthLogoutHandler.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/auth/service/AuthServiceImpl.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/jwt/JwtAuthenticationFilter.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/CustomAuthenticationManager.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/CustomUserDetailsService.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/SecurityConfig.java
  member-service/src/test/java/com/rljj/switchswitchmemberservice/global/config/jwt/JwtProviderTest.java
  switchswitch-common/src/main/java/com/rljj/switchswitchcommon/exception/NotAuthorizationException.java
  switchswitch-common/src/main/java/com/rljj/switchswitchcommon/jwt/JwtProvider.java
  switchswitch-common/src/main/java/com/rljj/switchswitchcommon/jwt/JwtProviderImpl.java
Labels: ⚙️ Refactoring

#21 member-service에서 불필요한 인증 과정 삭제
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/jwt/JwtAuthenticationFilter.java
Labels: ⚙️ Refactoring

#26 JWT 인증 리팩토링 및 로그인 필터 추가
  api-gateway/src/main/java/com/rljj/apigateway/filter/JwtAuthenticationFilter.java
  api-gateway/src/main/java/com/rljj/apigateway/redis/RedisConfig.java
  crawling-service/src/main/java/com/rljj/switchswitchcrawling/SwitchswitchcrawlingApplication.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/auth/controller/AuthController.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/auth/service/AuthService.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/auth/service/AuthServiceImpl.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/jwt/JwtAuthenticationFilter.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/CustomAuthenticationManager.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/CustomUserDetailsService.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/LoginAuthenticationFilter.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/SecurityConfig.java
  member-service/src/test/java/com/rljj/switchswitchmemberservice/global/config/jwt/JwtProviderTest.java
  switchswitch-common/src/main/java/com/rljj/switchswitchcommon/jwt/JwtProvider.java
  switchswitch-common/src/main/java/com/rljj/switchswitchcommon/jwt/JwtProviderImpl.java
  switchswitch-common/src/main/java/com/rljj/switchswitchcommon/jwt/JwtRedisService.java
  switchswitch-common/src/main/java/com/rljj/switchswitchcommon/jwt/JwtRedisServiceImpl.java
Labels: 🚀 Feature, ⚙️ Refactoring

#28 필터 오류 해결
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/auth/controller/AuthController.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/auth/service/AuthServiceImpl.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/member/service/MemberService.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/domain/member/service/MemberServiceImpl.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/jwt/JwtAuthenticationFilter.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/CustomAuthenticationManager.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/CustomUserDetailsService.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/LoginAuthenticationFilter.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/PasswordEncoderConfig.java
  member-service/src/main/java/com/rljj/switchswitchmemberservice/global/config/security/SecurityConfig.java
Labels: 🐛 BugFix
